// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/ai-assistant.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/analytics.ts";
import * as $$$$$$$$$$$2 from "./apps/deco/brand-assistant.ts";
import * as $$$$$$$$$$$3 from "./apps/deco/crux.ts";
import * as $$$$$$$$$$$4 from "./apps/deco/records.ts";
import * as $$$$$$$$$$$5 from "./apps/deco/sourei.ts";
import * as $$$$$$$$$$$6 from "./apps/deco/verified-reviews.ts";
import * as $$$$$$$$$$$7 from "./apps/deco/workflows.ts";
import * as $$$$$$$$$$$8 from "./apps/decohub.ts";
import * as $$$$$$$$$$$9 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/BlogPosts.tsx";
import * as $$$$$$1 from "./sections/Faq.tsx";
import * as $$$$$$2 from "./sections/Footer.tsx";
import * as $$$$$$3 from "./sections/Header.tsx";
import * as $$$$$$9 from "./sections/hero-1.tsx";
import * as $$$$$$10 from "./sections/hero-2.tsx";
import * as $$$$$$4 from "./sections/Hero.tsx";
import * as $$$$$$11 from "./sections/hero2.tsx";
import * as $$$$$$5 from "./sections/ImageWithParagraph.tsx";
import * as $$$$$$6 from "./sections/Logos.tsx";
import * as $$$$$$7 from "./sections/Testimonials.tsx";
import * as $$$$$$8 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "site/sections/BlogPosts.tsx": $$$$$$0,
    "site/sections/Faq.tsx": $$$$$$1,
    "site/sections/Footer.tsx": $$$$$$2,
    "site/sections/Header.tsx": $$$$$$3,
    "site/sections/hero-1.tsx": $$$$$$9,
    "site/sections/hero-2.tsx": $$$$$$10,
    "site/sections/Hero.tsx": $$$$$$4,
    "site/sections/hero2.tsx": $$$$$$11,
    "site/sections/ImageWithParagraph.tsx": $$$$$$5,
    "site/sections/Logos.tsx": $$$$$$6,
    "site/sections/Testimonials.tsx": $$$$$$7,
    "site/sections/Theme/Theme.tsx": $$$$$$8,
  },
  "apps": {
    "site/apps/deco/ai-assistant.ts": $$$$$$$$$$$0,
    "site/apps/deco/analytics.ts": $$$$$$$$$$$1,
    "site/apps/deco/brand-assistant.ts": $$$$$$$$$$$2,
    "site/apps/deco/crux.ts": $$$$$$$$$$$3,
    "site/apps/deco/records.ts": $$$$$$$$$$$4,
    "site/apps/deco/sourei.ts": $$$$$$$$$$$5,
    "site/apps/deco/verified-reviews.ts": $$$$$$$$$$$6,
    "site/apps/deco/workflows.ts": $$$$$$$$$$$7,
    "site/apps/decohub.ts": $$$$$$$$$$$8,
    "site/apps/site.ts": $$$$$$$$$$$9,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
